/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cie;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pushya
 */
public class booking_exam extends javax.swing.JFrame {

    /**
     * Creates new form booking_exam
     */
    public booking_exam() {
        initComponents();
    }

    Connection myConn = null;
        Statement myStmt = null;
        ResultSet myRs = null;
        PreparedStatement preparedStatement;
    /**
     * Creates new form BookAuditorium
     */
   void getConnectiondb() throws SQLException, ClassNotFoundException{
        // TODO code application logic here
       
      String user = "root";
      String pass = "test";

      myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cie_book", user, pass);
       

       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booking_date_val = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        booking_time_val = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        booking_date_val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booking_date_valActionPerformed(evt);
            }
        });

        jLabel1.setText("BOOK FOR DATE ");

        jLabel2.setText("BOOK");

        jLabel3.setText("BOOK FOR TIME");

        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(booking_date_val, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booking_time_val, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(294, 294, 294))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booking_date_val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booking_time_val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booking_date_valActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_date_valActionPerformed
        // TODO add your handling code here:
        booking_time_val.removeAllItems();
        int no_of_seats;
                
         try {
             getConnectiondb();
             
                String sel = booking_date_val.getSelectedItem().toString();
             //   System.out.println("Aud.ModifyEvents.eventname_valActionPerformed()"+sel);
             
            // Date date1=new SimpleDateFormat("yyy-mm-dd").parse(sel);  
SimpleDateFormat parser = new SimpleDateFormat("yyyy-mm-dd");
Date date1 = parser.parse(sel);
SimpleDateFormat formatter = new SimpleDateFormat("yyyy/mm/dd");
String dateStrReformatted = formatter.format(date1);
             
             
             
             String sql = ("SELECT distinct(sTime) FROM Exam where date= '"+dateStrReformatted+"'");
             Statement st = myConn.createStatement();

ResultSet rs = st.executeQuery(sql);
        while(rs.next())
        {
                 Time noofseats = rs.getTime("sTime");
       booking_time_val.addItem(noofseats.toString());
         
      
        }
    


 
         } catch (ParseException ex) {
            Logger.getLogger(booking_exam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(booking_exam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(booking_exam.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
        
        
        
    }//GEN-LAST:event_booking_date_valActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int no_of_seats;
                
         try {
             getConnectiondb();
             
                String sel = booking_date_val.getSelectedItem().toString();
             //   System.out.println("Aud.ModifyEvents.eventname_valActionPerformed()"+sel);
             
            // Date date1=new SimpleDateFormat("yyy-mm-dd").parse(sel);  
SimpleDateFormat parser = new SimpleDateFormat("yyyy-mm-dd");
Date date1 = parser.parse(sel);
SimpleDateFormat formatter = new SimpleDateFormat("yyyy/mm/dd");
String dateStrReformatted = formatter.format(date1);
        String starttime = booking_time_val.getSelectedItem().toString();
        
    DateFormat sdf = new SimpleDateFormat("hh:mm");
      Date sdate1 = null;
       
     try {
         sdate1 = sdf.parse(starttime);
         
     }   catch (ParseException ex) { 
             Logger.getLogger(examDetails.class.getName()).log(Level.SEVERE, null, ex);
         }
      Time stime = new Time(sdate1.getTime());
      
      
             
             System.out.println("button pressed with sTime "+stime+" sdate1" + sdate1);
            // String sql = ("SELECT distinct(sTime) FROM Exam where date= '"+dateStrReformatted+"'");
                          String selectusns = ("Select distinct(Registered.USN) from Registered,Exam\n" +
"where Registered.CID in\n" +
"(SELECT distinct(Course_ID) FROM Exam,Registered where Date = \""+dateStrReformatted+"\" and sTime = \""+stime+"\"and Exam.Course_ID\n" +
"=Registered.CID) order by 'asc';");

             String usncount =  ("select count(*) as usnc from\n" +
"(Select distinct(Registered.USN) from Registered,Exam\n" +
"where Registered.CID in\n" +
"(SELECT distinct(Course_ID) FROM Exam,Registered where Date = \""+dateStrReformatted+"\" and sTime = \""+stime+"\"and Exam.Course_ID\n" +
"=Registered.CID) order by 'asc') as usncount");
             
             
             Statement st = myConn.createStatement();
 Statement st2 = myConn.createStatement();
ResultSet rsusns = st.executeQuery(selectusns);
ResultSet rsusncount = st2.executeQuery(usncount);
 while(rsusncount.next()){
        System.out.println("usn count = "+rsusncount.getInt("usnc"));
        }
        while(rsusns.next())
        {
                String usns = rsusns.getString("USN");
            System.out.println(usns);
            
            
         
      
        }
       
    


 
         } catch (ParseException ex) {
            Logger.getLogger(booking_exam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(booking_exam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(booking_exam.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking_exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking_exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking_exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking_exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking_exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> booking_date_val;
    public javax.swing.JComboBox<String> booking_time_val;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
