package Aud;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LENOVO
 */
public class ModifyAuditorium extends javax.swing.JFrame {

     int evntid;

    /**
     * Creates new form ModifyEvents
     */
    
 
   
    
    /**
     * Creates new form ModifyAuditorium
     */
    public ModifyAuditorium() {
        initComponents();
        //[39,229,217]
         getContentPane().setBackground(new java.awt.Color(1,1,1));
    }
       
    
     Connection myConn = null;
        Statement myStmt = null;
        ResultSet myRs = null;
        PreparedStatement preparedStatement;
    /**
     * Creates new form BookAuditorium
     */
   void getConnectiondb() throws SQLException, ClassNotFoundException{
        // TODO code application logic here
       
      String user = "root";
      String pass = "test";

      myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/aud_jdbms",user,pass);
      

       
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modifyauditorium = new javax.swing.JLabel();
        auditoriumnumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        auditoriumnumberval = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        auditoriumnumber2 = new javax.swing.JLabel();
        auditoriumnumber2val = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        aud_statusval = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        aud_countval = new javax.swing.JTextField();
        audno_val = new javax.swing.JComboBox<>();
        save1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modifyauditorium.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 48)); // NOI18N
        modifyauditorium.setForeground(new java.awt.Color(254, 254, 254));
        modifyauditorium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyauditorium.setText("MODIFY AUDITORIUM");

        auditoriumnumber.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        auditoriumnumber.setForeground(new java.awt.Color(254, 254, 254));
        auditoriumnumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auditoriumnumber.setText("AUDITORIUM NUMBER");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NUMBER OF SEATS");

        auditoriumnumberval.setBackground(new java.awt.Color(1, 1, 1));
        auditoriumnumberval.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        auditoriumnumberval.setForeground(new java.awt.Color(254, 254, 254));

        save.setBackground(new java.awt.Color(45, 99, 95));
        save.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        save.setForeground(new java.awt.Color(254, 254, 254));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        auditoriumnumber2.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        auditoriumnumber2.setForeground(new java.awt.Color(254, 254, 254));
        auditoriumnumber2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auditoriumnumber2.setText("AUDITORIUM NUMBER");

        auditoriumnumber2val.setBackground(new java.awt.Color(1, 1, 1));
        auditoriumnumber2val.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        auditoriumnumber2val.setForeground(new java.awt.Color(254, 254, 254));

        delete.setBackground(new java.awt.Color(45, 99, 95));
        delete.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(254, 254, 254));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(45, 99, 95));
        back.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        back.setForeground(new java.awt.Color(254, 254, 254));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("STATUS");

        aud_statusval.setBackground(new java.awt.Color(1, 1, 1));
        aud_statusval.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        aud_statusval.setForeground(new java.awt.Color(254, 254, 254));
        aud_statusval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aud_statusvalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("COUNT");

        aud_countval.setBackground(new java.awt.Color(1, 1, 1));
        aud_countval.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        aud_countval.setForeground(new java.awt.Color(254, 254, 254));

        audno_val.setBackground(new java.awt.Color(1, 1, 1));
        audno_val.setEditable(true);
        audno_val.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        audno_val.setForeground(new java.awt.Color(254, 254, 254));
        audno_val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audno_valActionPerformed(evt);
            }
        });

        save1.setBackground(new java.awt.Color(45, 99, 95));
        save1.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        save1.setForeground(new java.awt.Color(254, 254, 254));
        save1.setText("ADD NEW AUDITORIUM");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("MODIFY AUDITORIUM");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("REMOVE AUDITORIUM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(352, 352, 352)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(modifyauditorium, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(auditoriumnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(auditoriumnumber2val, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(auditoriumnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(audno_val, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(aud_countval, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(auditoriumnumberval, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(aud_statusval, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(225, 225, 225)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modifyauditorium, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(auditoriumnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(audno_val, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(auditoriumnumberval, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aud_statusval, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aud_countval)
                                .addGap(4, 4, 4)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auditoriumnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auditoriumnumber2val, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       new BookAuditorium().setVisible(true);
           this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void aud_statusvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aud_statusvalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aud_statusvalActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String aud_no2;
        aud_no2 = auditoriumnumber2val.getText();
        
         try {
             getConnectiondb();
             String sql = "Delete from Auditoriums  where Aud_ID = ?";
            PreparedStatement pst = myConn.prepareStatement(sql);
   pst.setString(1, aud_no2);
   pst.execute();
         } catch (SQLException ex) {
             Logger.getLogger(ModifyAuditorium.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(ModifyAuditorium.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:

      String aud_no;
      int no_of_seats;
      String status;
       int count;
      
        //id = Integer.parseInt(eventid.getText());
         String sel = audno_val.getSelectedItem().toString();
        aud_no = sel;
        no_of_seats = Integer.parseInt(auditoriumnumberval.getText());
        status = aud_statusval.getText();
        count = Integer.parseInt(aud_countval.getText());
   
        try {
            getConnectiondb();
             String sql = "update Auditoriums set NoofSeats=? ,Status=?,Count= ? where Aud_ID=?";
            PreparedStatement pst = myConn.prepareStatement(sql);
   pst.setInt(1, no_of_seats);
    pst.setString(2,status);
     pst.setInt(3, count);
     


   pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(ModifyEvents.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ModifyEvents.class.getName()).log(Level.SEVERE, null, ex);
        }
          System.out.print("done");   








        
        
    }//GEN-LAST:event_saveActionPerformed

    private void audno_valActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audno_valActionPerformed
        // TODO add your handling code here:
        audno_val.setEditable(false);
        
        int no_of_seats;
                
         try {
             getConnectiondb();
             
                String sel = audno_val.getSelectedItem().toString();
             //   System.out.println("Aud.ModifyEvents.eventname_valActionPerformed()"+sel);
             String sql = ("SELECT * FROM Auditoriums where Aud_ID = '"+sel+"'");
             Statement st = myConn.createStatement();

ResultSet rs = st.executeQuery(sql);
        while(rs.next())
        {
  int noofseats = rs.getInt("NoofSeats");
 String status = rs.getString("Status");
 int count = rs.getInt("Count");
 
 
   auditoriumnumberval.setText(""+noofseats);
    aud_statusval.setText(" "+status);
      aud_countval.setText(" "+count);
      
        }
    


 
         } catch (SQLException ex) {
             Logger.getLogger(ModifyEvents.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(ModifyEvents.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_audno_valActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        // TODO add your handling code here:
        
          String aud_id,status;
        String eName,sTime = null,eTime = null;
        int noofseat,count;
        
        aud_id = audno_val.getSelectedItem().toString();
        noofseat = Integer.parseInt(auditoriumnumberval.getText());
       
        status = aud_statusval.getText();
     
        String query = "insert into Auditoriums (Aud_ID, NoofSeats, Status) " + 
                                   "values (?,?,?)"; 
     try {
        getConnectiondb();

         preparedStatement = myConn.prepareStatement(query);

         preparedStatement.setString(1,aud_id);
         preparedStatement.setInt(2,noofseat);
          preparedStatement.setString(3,status);
        
         

         // Execute statement and return the number of rows affected
         int rowCount = preparedStatement.executeUpdate();
         System.out.println("Number of rows affected: " + rowCount);
      } catch (SQLException ex) {
         Logger.getLogger(BookAuditorium.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(BookAuditorium.class.getName()).log(Level.SEVERE, null, ex);
     } finally {
            try {
                preparedStatement.close();
            } catch (SQLException ex) {
                Logger.getLogger(BookAuditorium.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                myConn.close();
            } catch (SQLException ex) {
                Logger.getLogger(BookAuditorium.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
        
        
        
        
        
    }//GEN-LAST:event_save1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyAuditorium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyAuditorium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyAuditorium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyAuditorium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyAuditorium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aud_countval;
    private javax.swing.JTextField aud_statusval;
    private javax.swing.JLabel auditoriumnumber;
    private javax.swing.JLabel auditoriumnumber2;
    private javax.swing.JTextField auditoriumnumber2val;
    private javax.swing.JTextField auditoriumnumberval;
    public javax.swing.JComboBox<String> audno_val;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel modifyauditorium;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    // End of variables declaration//GEN-END:variables
}
